### ISSUE TITLE
eutils fails on url import

### ISSUE THREAD

**Issue by xbaro** [TailorDev/django-tailordev-biblio#36]
With eutils 0.5.2 the client module does not exist.  In order to work, the following changes are required:

**td_biblio/utils/loaders.py**

_**line 13:**_
import eutils.client => import eutils

_**line 226:**_
eutils.client.Client()  => eutils.Client()

**Comment by jmaupetit** [comment]
Hi @xbaro! Thanks for the report :pray: As you know how to fix it, can you submit a pull request?

**Comment by xbaro** [comment]
Pull request created:

https://github.com/TailorDev/django-tailordev-biblio/pull/37
